

name: Update streams
on:
  schedule:
    - cron: "30 */4 * * *"
  workflow_dispatch:

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: update streams
        run: |
          #!/bin/bash
          sed -i "/live_tvi\/live_tvi/ c https://video-auth6.iol.pt/live_tvi/live_tvi/playlist.m3u8?wmsAuthSign=$(wget https://services.iol.pt/matrix?userId= -o /dev/null -O -)/" Freetv.m3u
          sed -i "/live_cnn/ c https://video-auth7.iol.pt/live_cnn/live_cnn/playlist.m3u8?wmsAuthSign=$(wget https://services.iol.pt/matrix?userId= -o /dev/null -O -)/" Freetv.m3u
          sed -i "/live_tvi_internacional/ c https://video-auth6.iol.pt/live_tvi_internacional/live_tvi_internacional/playlist.m3u8?wmsAuthSign=$(wget https://services.iol.pt/matrix?userId= -o /dev/null -O -)/" Freetv.m3u

      - name: update total channels
        run: |
          TOTAL=$(grep -c '^#EXTINF:-1' Freetv.m3u)
          sed -i "s/^# (●) Total Channels:.*/# (●) Total Channels: $TOTAL/" Freetv.m3u
      
      - name: setup git config
        run: |
          git config user.name "m3u updater bot"
          git config user.email "<inspirationlivetv@gmail.com>"

      - name: commit
        run: |
          git pull
          git add Freetv.m3u
          git commit -m "Update streams"
          git push origin live


        
